### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by ricardoroehe** [GDquest/BPSRender#4]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
BPSrender does not run.

**What is the expected behavior?**
BPSrender to run.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
1) Browse to BPSrender folder included in Blender (/home/user/bin/blender/2.83/scripts/addons/power_sequencer/scripts/BPSRender, in my case);
2) on terminal, run: `python3 -m bpsrender file.blend`;
3) error received:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/bin/blender/2.83/scripts/addons/power_sequencer/scripts/BPSRender/bpsrender/__main__.py", line 31, in <module>
    from .calls import call
  File "/home/user/bin/blender/2.83/scripts/addons/power_sequencer/scripts/BPSRender/bpsrender/calls.py", line 26, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

```

## Other ##

**Other information** 

Running:
- Blender: 2.83.0;
- OS: Linux Mint 19.2 Cinnamon;
- Processor: AMD Athlon(tm) II X3 425 Processor × 3;
- Graphics: NVIDIA Corporation GF116 [GeForce GTX 550 Ti]; 
- RAM: 15.7 GiB.

**Questions** 
1) Is it really OK to call BPSrender from the folder included in Blender's BPS addon? Is that the problem?
2) There is no way to use BPSrender inside Blender currently, right?

**Comment by NathanLovato** [comment]
I think we should remove that dependency on tqdm. I'll open a task for that.

**Comment by ricardoroehe** [comment]
Sorry, it was just a simple matter of missing the "tqdm" module.

Solved with:

1. `sudo apt install python3-pip`
2. `python3 -m pip install tqdm`

Now `python3 -m bpsrender` runs (although I'm having another issues...).
